# Generated by Django 5.1.1 on 2024-10-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='type_ajout',
            field=models.CharField(choices=[('upload', 'Upload'), ('lien', 'Lien')], default='upload', max_length=10),
        ),
    ]
