# Generated by Django 5.1.1 on 2024-10-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cours_type_ajout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='lien',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='type_ajout',
        ),
    ]
