# Generated by Django 5.0.6 on 2024-10-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_cours_lien_remove_cours_type_ajout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='cours_fichiers/'),
        ),
    ]
