# Generated by Django 5.0.6 on 2024-10-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_cours_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
