# Generated by Django 5.0.6 on 2024-10-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_cours_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='image',
        ),
    ]
