# Generated by Django 5.1.1 on 2024-10-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_cours_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='genere_par_ia',
            field=models.BooleanField(default=False),
        ),
    ]
